name: Deploy

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Run a one-line script
      run: echo Hello, world!

    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.

    - name: Deploy to Heroku
      uses: AkhileshNS/heroku-deploy@v1.0.0
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "calpoly-csai-groupme-bot"
        heroku_email: "mike.fekadu@gmail.com"
