name: Deploy To Heroku

on:
  push:
    branches: 
      - master

jobs:
  deploy:
    name: deploy to heroku
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Run a one-line script
      env:
        HEROKU_EMAIl: ${{ secrets.HEROKU_EMAIL }}
      run: echo Hello, world! $HEROKU_EMAIL

    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.

    - name: login
      uses: actions/heroku@master
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      with:
        args: container:login

    - name: push
      uses: actions/heroku@master
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      with:
        args: container:push -a calpoly-csai-groupme-bot web

    - name: release
      uses: actions/heroku@master
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      with:
        args: container:release -a calpoly-csai-groupme-bot web
